#!/bin/bash

echo serversync was launched: >> /tmp/serversync.txt
date >> /tmp/serversync.txt
echo ===================== >> /tmp/serversync.txt

# brutally kill mplayer and omxplayer no matter what was using it before
killall mplayer
killall omxplayer

# check if mplayer is installed
# if mplayer or omxplayer is installed, set it to path (still need to write this part)

/usr/bin/which mplayer
/usr/bin/which omxplayer
/usr/bin/which omxplayer-sync
# see if the command was run with a movie path, if so play it
# if not, ask for a path
# if no path given, play a default video (maybe oof stream?)

# display requirements and preferred mothods of using

# start the server



if [ -z "$1" ] #check if run with user input
  then
    echo you can specify a file to play by running this command with a path
    echo ex: ./serverstart ~/movies/video_art/eyeball-SD-BW-slow.mp4
    #nohup mplayer -udp-master -udp-ip 192.168.0.255 -loop 0 ~/movies/eyeball.mp4 >/dev/null 2>&1 &
    nohup omxplayer-sync -muv ~/movies/omxtest.mov >/dev/null 2>&1 & # l = slave u = loop v = verbose & # m = master  u = loop v = verbose
else
  echo Playing from user input $1
  #nohup mplayer -fs -zoom -udp-master -udp-ip 192.168.0.255 -loop 0 $1 >/dev/null 2>&1 &
  nohup omxplayer-sync -muv $1 >/dev/null 2>&1 & # m = master u = loop v = verbose
fi
