#!/bin/bash

# brutally kill mplayer no matter what was using it before
killall mplayer

# check if mplayer is installed
# if mplayer is installed, set it to path

/usr/bin/which mplayer

# see if the command was run with a movie path, if so play it
# if not, ask for a path
# if no path given, play a default video (maybe oof stream?)

# display requirements and preferred mothods of using

# start the server



if [ -z "$1" ] #check if run with user input
  then
    echo you can specify a file to play by running this command with a path
    echo ex: ./serverstart ~/movies/video_art/eyeball-SD-BW-slow.mp4
    nohup mplayer -udp-master -udp-ip 192.168.0.255 -loop 0 /Users/lorenrisker/Movies/video_art/eyeball-SD-BW-slow-prores.mov &
else
  echo Playing from user input $1
  nohup mplayer -fs -zoom -udp-master -udp-ip 192.168.0.255 -loop 0 $1 &
fi
